# HTTP 
server:
  port: ${PORT:7777}

spring:
  application:
    name: comic

management:
  security:
    enabled: false

# Discovery Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.microservices.scn: 'DEBUG'

spring:
   rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest